services:
  postgis:
    image: pgpointcloud/pointcloud 
    container_name: postgis_terrain
    environment:
      POSTGRES_DB: terrain
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./enable_extensions.sql:/docker-entrypoint-initdb.d/enable_extensions.sql
      

volumes:
  postgis_data: