services:
  postgis:
    image: postgis/postgis
    container_name: postgis_terrain
    environment:
      POSTGRES_DB: terrain
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data: