name: terrain_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - requests
  - whitebox
  - rasterio
  - gdal
  - pdal=2.6.2
  - python-pdal
  - laspy
  - pyproj
  - psycopg2